server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_vue?serverTimezone=GMT%2b8
    username: root
    password: root

  thymeleaf:
    cache: false

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

  type-aliases-package: cn.blue.mall.bean

logging:
  level:
    cn.blue: trace



